stages:
  - publish
  - update

mirror:
  stage: publish
  script:
    - setsid ./ci/mirror.sh
  rules: 
    - if: $CI_COMMIT_MESSAGE =~ /(Update date terms.html)/
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /main/ 
  tags:
    - mirror

terms:
  stage: update
  script:
    - setsid ./ci/update-terms.sh
  rules: 
    - if: $CI_COMMIT_MESSAGE =~ /(Update date terms.html)/
    - if: $CI_COMMIT_REF_NAME =~ /main/ 
      changes:
        - .gitlab-ci.yml
        - admin/*
        - admin/utils/*
        - ci/update-terms.sh
        - ci/compute-env.sh
  tags:
    - mastodon
