version: "3.3"

services: 
  update-terms:
    container_name: mastodon-update-terms
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - mastodon.env
    volumes:
      - ./terms.html:/app/terms.html
    command: ["python3", "/app/terms.py"]
  update-about:
    container_name: mastodon-update-about
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - mastodon.env
    volumes:
      - ./about.md:/app/about.md
    command: ["python3", "/app/about.py"]
  update-rules:
    container_name: mastodon-update-rules
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - mastodon.env
    volumes:
      - ./config.yaml:/app/config.yaml
    command: ["python3", "/app/rules.py"]
  update-css:
    container_name: mastodon-update-css
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - mastodon.env
    volumes:
      - ./config.yaml:/app/config.yaml
    command: ["python3", "/app/css.py"]
  update-ban:
    container_name: mastodon-update-ban
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - mastodon.env
    volumes:
      - ./config.yaml:/app/config.yaml
    command: ["python3", "/app/ban.py"]
