version: "3.3"

services: 
  update-terms:
    container_name: mastodon-update-terms
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - mastodon.env
    volumes:
      - ./terms.html:/app/terms.html
    command: ["python3", "/app/terms.py"]
  update-rules:
    container_name: mastodon-update-rules
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - mastodon.env
    volumes:
      - ./config.yaml:/app/config.yaml
    command: ["python3", "/app/rules.py"]
